Create terraform main.tf file
Gev544/devops-hti-2023 pull request #24
Opened 2024-01-20 09:19 UTC by SevakIvanyan

2024-01-20 10:51 UTC, Gev544 commented on homework-20-01-24/sevak-ivanyan/main.tf
> +  route {
no need for ipv6

2024-01-20 10:51 UTC, Gev544 commented on homework-20-01-24/sevak-ivanyan/main.tf
> +  ingress {
80 port not needed

2024-01-20 10:52 UTC, Gev544 requested changes
Keep logical separation of files.
Provider information must be in separate prodiver.tf file provider + backend...
Networking staff must be in vpc.tf or networking.tf vpc + igw + routings...
ec2 staff must be in ec2.tf or instances.tf ec2 instance + key pair + sg...
Use variables with separate file

2024-01-23 12:21 UTC, shtajiryan approved these changes

2024-02-05 20:12 UTC, closed without merging