AMkrtchyan_20_01
Gev544/devops-hti-2023 pull request #25
Opened 2024-01-20 11:11 UTC by amiamahy

2024-01-20 11:14 UTC, Gev544 commented on homework-20-01-24/Aren-Mkrtchyan/terraform_test/ssh.tf
Must be part of ec2.tf

2024-01-20 11:14 UTC, Gev544 commented on homework-20-01-24/Aren-Mkrtchyan/terraform_test/gateway.tf
Must be part of Vpc.tf

2024-01-20 11:16 UTC, Gev544 requested changes
Use variables for regions, ami etc...
create separate variables.tf file to put vars there.

2024-01-20 11:16 UTC, Gev544 commented on homework-20-01-24/Aren-Mkrtchyan/terraform_test/subnet.tf
must be part of vpc.tf

2024-01-20 11:16 UTC, Gev544 commented on homework-20-01-24/Aren-Mkrtchyan/terraform_test/route.tf
must be part of vpc

2024-01-23 08:36 UTC, amiamahy reviewed
repaired

2024-01-23 09:22 UTC, amiamahy reviewed
added docker files

2024-01-23 09:25 UTC, shtajiryan requested changes
Move the docker homework into classwork-13-01-24, make a separate branch and PR for it. The branch logic should be, aren-mkrtchyan-classwork-13-01-24. Revert your latest commit on this branch so I can merge terraform hw.

Also remove files from terraform_test folder, they can be in the root of aren-mkrtchyan inside homework-20-01-24

2024-01-23 10:52 UTC, closed without merging